title: "El's Corner"
author: "El"
baseurl: "" # change to "/repo-name" if not using username.github.io
url: "" # change to "https://username.github.io"
description: >
  engineering manager. photographer. builder of things.

remote_theme: riggraz/no-style-please

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# appearance: "dark" enables dark mode, "light" for light, "auto" for system
theme_config:
  appearance: "dark"
  show_description: true
  date_format: "%Y-%m-%d"

  back_home:
    text: "< back to home"
    show: true

# Build settings
markdown: kramdown
